const constants = {

    SHOW_SIGN_UP_DIALOG: "SHOW_SIGN_UP_DIALOG",
    HIDE_SIGN_UP_DIALOG: "HIDE_SIGN_UP_DIALOG",
    SIGN_UP: "SIGN_UP",
    SIGN_UP_SUCCESFUL: "SIGN_UP_SUCCESFUL",

    LOGIN:"LOGIN",
    SHOW_LOGIN_FORM : "SHOW_LOGIN_FORM",
    HIDE_LOGIN_FORM : "HIDE_LOGIN_FORM",

    CREATE_ACCOUNT : "CREATE_ACCOUNT",
    SAVE_USERNAME : "SAVE_USERNAME",
    SAVE_FIRSTNAME: "SAVE_FIRSTNAME",
    SAVE_LASTNAME : "SAVE_LASTNAME",
    SAVE_PASSWD : "SAVE_PASSWD",
    SAVE_REENTERED_PASSWD: "SAVE_REENTERED_PASSWD",

    PASSWORDS_NOT_THE_SAME: "PASSWORDS_NOT_THE_SAME",
    USERNAME_TAKEN: "USERNAME_TAKEN",
    CREATING_ACCOUNT_SUCCESS : "CREATING_ACCOUNT_SUCCESS",

    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",

    ON_HOME_CLICK : "ON_HOME_CLICK",
    ON_POKEMON_CLICK : "ON_POKEMON_CLICK",
    ON_USERS_CLICK : "ON_USERS_CLICK",
    ON_TRAINGINGS_CLICK : "ON_TRAINGINGS_CLICK",

    POKEMON_ADMIN: "POKEMON_ADMIN",
    TRAINING_ADMIN: "TRAINING_ADMIN",
    USERS_ADMIN: "USERS_ADMIN",
    SHOW_ADD_POKEMON_ADMIN_PANEL: "SHOW_ADD_POKEMON_ADMIN_PANEL",
    SHOW_ADD_TRAINING_ADMIN_PANEL: "SHOW_ADD_TRAINING_ADMIN_PANEL",

    ON_ADMIN_DELETE_POKEMON_SUCCESS : "ON_ADMIN_DELETE_POKEMON_SUCCESS",
    ON_ADMIN_DELETE_POKEMON_FAILED : "ON_ADMIN_DELETE_POKEMON_FAILED",
    ON_ADMIN_DELETE_TRAINING : "ON_ADMIN_DELETE_TRAINING",

    SET_SEARCH_VALUE: "SET_SEARCH_VALUE",
    SET_SORT_VALUE: "SET_SORT_VALUE"

};

export default constants
