const constants = {

    SHOW_SIGN_UP_DIALOG: "SHOW_SIGN_UP_DIALOG",
    HIDE_SIGN_UP_DIALOG: "HIDE_SIGN_UP_DIALOG",
    SIGN_UP: "SIGN_UP",
    SIGN_UP_SUCCESFUL: "SIGN_UP_SUCCESFUL",

    LOGIN:"LOGIN",
    SHOW_LOGIN_FORM : "SHOW_LOGIN_FORM",
    HIDE_LOGIN_FORM : "HIDE_LOGIN_FORM",

    CREATE_ACCOUNT : "CREATE_ACCOUNT",
    SAVE_USERNAME : "SAVE_USERNAME",
    SAVE_FIRSTNAME: "SAVE_FIRSTNAME",
    SAVE_LASTNAME : "SAVE_LASTNAME",
    SAVE_PASSWD : "SAVE_PASSWD",
    SAVE_REENTERED_PASSWD: "SAVE_REENTERED_PASSWD",
    SAVE_NEW_POKEMON_NAME: "SAVE_NEW_POKEMON_NAME",

    PASSWORDS_NOT_THE_SAME: "PASSWORDS_NOT_THE_SAME",
    USERNAME_TAKEN: "USERNAME_TAKEN",
    CREATING_ACCOUNT_SUCCESS : "CREATING_ACCOUNT_SUCCESS",

    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",

    ON_HOME_CLICK : "ON_HOME_CLICK",
    ON_POKEMON_CLICK : "ON_POKEMON_CLICK",
    ON_USERS_CLICK : "ON_USERS_CLICK",
    ON_TRAINGINGS_CLICK : "ON_TRAINGINGS_CLICK",

    POKEMON_ADMIN: "POKEMON_ADMIN",
    TRAINING_ADMIN: "TRAINING_ADMIN",
    USERS_ADMIN: "USERS_ADMIN",
    SHOW_ADD_POKEMON_ADMIN_PANEL: "SHOW_ADD_POKEMON_ADMIN_PANEL",
    SHOW_ADD_TRAINING_ADMIN_PANEL: "SHOW_ADD_TRAINING_ADMIN_PANEL",

    ON_ADMIN_DELETE_POKEMON_SUCCESS : "ON_ADMIN_DELETE_POKEMON_SUCCESS",
    ON_ADMIN_DELETE_POKEMON_FAILED : "ON_ADMIN_DELETE_POKEMON_FAILED",
    ON_ADMIN_DELETE_USER : "ON_ADMIN_DELETE_USER",
    ON_ADMIN_DELETE_TRAINING : "ON_ADMIN_DELETE_TRAINING",

    ON_LOAD_PICTURE: "ON_LOAD_PICTURE",
    SET_SEARCH_VALUE: "SET_SEARCH_VALUE",
    SET_SORT_VALUE: "SET_SORT_VALUE",
    GET_TRAINING_TO_EDIT : "GET_TRAINING_TO_EDIT",
    LOG_OUT : "LOG_OUT",

    NEW_POKEMON_ADDED: "NEW_POKEMON_ADDED",
    NEW_TRAINING_ADDED: "NEW_TRAINING_ADDED",
    EDITED_TRAINING_TO_EDIT : "EDITED_TRAINING_TO_EDIT",
    EDITED_TRAINING : "EDITED_TRAINING",
    EDIT_TRAINING_NAME : "EDIT_TRAINING_NAME",
    EDIT_TRAINING_HEALTH : "EDIT_TRAINING_HEALTH",
    EDIT_TRAINING_ATTACK : "EDIT_TRAINING_ATTACK",
    EDIT_TRAINING_AGILITY : "EDIT_TRAINING_AGILITY",
    EDIT_TRAINING_DURATION : "EDIT_TRAINING_DURATION",
    EDIT_TRAINING_DEFENCE : "EDIT_TRAINING_DEFENCE",
};

export default constants
